_format_version: "3.0"
_transform: true

services:
  - name: tools-service-all
    url: http://5.35.5.126:8085
    port: 8085
    protocol: http
    routes:
      - name: api-tools-all
        methods:
          - GET
        paths:
          - /api/v1/tools/
          - /api/v1/categories/
          - /api/v1/brands/
        strip_path: false

  - name: tools-service-auth
    url: http://5.35.5.126:8085
    plugins:
      - name: oidc
        config:
          client_id: kong
          client_secret: JRjwzr1UjoFfDcxVxE6ey1e9AuDIrzqm
          discovery: https://auth.rentool36.ru/realms/rentool/.well-known/openid-configuration
          introspection_endpoint: https://auth.rentool36.ru/realms/rentool/protocol/openid-connect/token/introspect
          realm: rentool
    port: 8085
    protocol: http
    routes:
      - name: api-tools-auth
        methods:
          - POST
          - PUT
          - DELETE
        paths:
          - /api/v1/tools/
          - /api/v1/categories/
          - /api/v1/brands/
        strip_path: false

  - name: users-service-all
    url: http://5.35.5.126:8087
    port: 8087
    protocol: http
    routes:
      - name: api-users-all
        methods:
          - POST
        paths:
          - /api/v1/users/
        strip_path: false

  - name: users-service-auth
    url: http://5.35.5.126:8087
    plugins:
      - name: oidc
        config:
          client_id: kong
          client_secret: JRjwzr1UjoFfDcxVxE6ey1e9AuDIrzqm
          discovery: https://auth.rentool36.ru/realms/rentool/.well-known/openid-configuration
          introspection_endpoint: https://auth.rentool36.ru/realms/rentool/protocol/openid-connect/token/introspect
          realm: rentool
    port: 8087
    protocol: http
    routes:
      - name: api-users-auth
        methods:
          - GET
          - PATCH
        paths:
          - /api/v1/users/
        strip_path: false

  - name: rent-service-all
    url: http://5.35.5.126:8086
    port: 8086
    protocol: http
    routes:
      - name: api-rent-all
        methods:
          - GET
        paths:
          - /api/v1/advertising/
        strip_path: false

  - name: rent-service-auth
    url: http://5.35.5.126:8086
    port: 8086
    protocol: http
    plugins:
      - name: oidc
        config:
          client_id: kong
          client_secret: JRjwzr1UjoFfDcxVxE6ey1e9AuDIrzqm
          discovery: https://auth.rentool36.ru/realms/rentool/.well-known/openid-configuration
          introspection_endpoint: https://auth.rentool36.ru/realms/rentool/protocol/openid-connect/token/introspect
          realm: rentool
    routes:
      - name: api-rent-auth
        methods:
          - POST
          - GET
          - PATCH
        paths:
          - /api/v1/rents/
        strip_path: false

