spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://${USER_DB_HOST:localhost}:${USER_DB_PORT:5437}/${USER_DB_NAME:user}
    username: ${USER_USERNAME}
    password: ${USER_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: 8087

logging:
  config: classpath:log4j2-plain.xml

keycloak:
  url: ${KEYCLOACK_HOST:http://localhost:8180}
  realm: ${REALM_NAME:rentool}
  clientId: ${CLIENT_ID:kong}
  clientSecret: ${CLIENT_SECRET:iL4DtVfRHYgJMi278u5n10n3l0aJ516Q}
  username: ${KEYCLOAK_USERNAME:backend@backend}
  password: ${KEYCLOAK_PASSWORD:123456789}
